spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiev_weather_data
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: false
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 2000
        order_inserts: true